<<<<<<< HEAD
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using Unity.VisualScripting;
using UnityEngine;
=======
ï»¿using System.Collections;
using System.Collections.Generic;
using UnityEditor.Tilemaps;
using UnityEngine;
using UnityEngine.Audio;
>>>>>>> 22ff9ed88032a66f3cc0fc3a068ec87347d487ea

public class PlayerController : MonoBehaviour
{
    Rigidbody2D rb;
<<<<<<< HEAD
    public float speed = 3.0f; // ÀÌµ¿ ¼Óµµ

    float axisH, axisV;
    public static string gameState = "playing";

    //SPUM ¿¡¼ÂÀÇ  ¾Ö´Ï¸ÞÀÌ¼Ç Á¦¾î¿ë
    SPUM_Prefabs spum;
    Vector2 lastMoveDir = Vector2.down;  // ¸¶Áö¸· ¹Ù·Îº» ¹æÇâ Ç¥½Ã
    const float moveDeadZone = 0.05f; // ¹Ì¼¼¿òÁ÷ÀÓ ¹«½Ã
    private PlayerState currentState = PlayerState.IDLE;

    float baseScaleX = 1f;
    float lastSign = -1f;
    Transform visual;

    private void Awake()
    {
        spum = GetComponent<SPUM_Prefabs>();
        spum.OverrideControllerInit();
        visual = spum._anim.transform;
    }
=======
    public float speed = 3.0f; //ì´ë™ì†ë„
    public string upAni = "PlayerUp";
    public string downAni = "PlayerDown";
    public string leftAni = "PlayerLeft";
    public string rightAni = "PlayerRight";
    public string deadAni = "PlayerDead";

    string nowAni = ""; //í˜„ìž¬ ì• ë‹ˆë©”ì´ì…˜
    string oldAni = ""; //ì´ì „ ì• ë‹ˆë©”ì´ì…˜

    float axisH, axisV;
    public float angleZ = -90.0f; // íšŒì „ê°

    bool isMoving = false; //ì´ë™ì—¬ë¶€

    public static int hp = 3; //ìºë¦­í„° ìƒëª…ë ¥
    public static string gameState; //ê²Œìž„ ìƒíƒœ -ê²Œìž„ì¤‘(playing),ê²Œìž„ì˜¤ë²„(gameOver) 
    bool inDamage = false; //ë°ë¯¸ì§€ ì—¬ë¶€




>>>>>>> 22ff9ed88032a66f3cc0fc3a068ec87347d487ea

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
<<<<<<< HEAD
        //gameState = "playing";
    }

    // Update is called once per frame
    void Update()
    {

        //Debug.Log("gameState ::::::" + gameState );

        if (gameState == "Battle")
        {
            currentState = PlayerState.IDLE; // ¿òÁ÷ÀÓ ¸·±â
            return;
        }


        if (gameState != "playing") return; 
                                                       
      
         axisH = Input.GetAxisRaw("Horizontal");  // ÁÂ¿ì ÀÌµ¿Å°
         axisV = Input.GetAxisRaw("Vertical"); // »óÇÏ ÀÌµ¿Å°


        if (moveDeadZone < Mathf.Abs(axisH))
        {
            //ÁÂ¿ì ÀÌµ¿ ¹æÇâ
            lastSign = axisH > 0 ? -1f : 1f;
            var s = visual.localScale;
            s.x = baseScaleX * lastSign;
            visual.localScale = s;
        }


        Vector2 input;
        input.x= axisH;
        input.y= axisV;
        input.Normalize();

        if (input.magnitude > 0.01f)
            currentState = PlayerState.MOVE;
        else
            currentState = PlayerState.IDLE;

        if (Input.GetKeyDown(KeyCode.Space))
            currentState = PlayerState.ATTACK;

            var animList = spum.StateAnimationPairs[currentState.ToString()];
        int index = 0;
        spum.PlayAnimation(currentState, index);
=======
        oldAni = downAni;
        gameState = "playing";
        hp = PlayerPrefs.GetInt("PlayerHP");




    }






    void Update()
    {
        if (gameState != "playing" || inDamage) return; // ê²Œìž„ìƒíƒœê°€ í”Œë ˆì´ì¤‘ì´ ì•„ë‹ˆê±°ë‚˜
                                                        // ë°ë¯¸ì§€ ìž…ê³  ìžˆëŠ”ì¤‘ì´ë©´ ì´ë™ ëª»í•¨
        if (isMoving == false)
        {
            axisH = Input.GetAxisRaw("Horizontal");  // ì¢Œìš° ì´ë™í‚¤
            axisV = Input.GetAxisRaw("Vertical");    // ìƒí•˜ ì´ë™í‚¤
        }

        //í‚¤ìž…ë ¥ìœ¼ë¡œ ê°ë„ë¥¼ êµ¬í•˜ê³  ê°ë„ì— ë”°ë¼ ì• ë‹ˆë©”ì´ì…˜ ë³€ê²½
        Vector2 fromPt = transform.position;
        Vector2 toPt = new Vector2(fromPt.x + axisH, fromPt.y + axisV);

        angleZ = GetAngle(fromPt, toPt);

        if (angleZ >= -45 && angleZ < 45)
        {
            nowAni = rightAni;
        }
        else if (angleZ >= 45 && angleZ <= 135)
        {
            nowAni = upAni;
        }
        else if (angleZ > 135 && angleZ < 225)
        {
            nowAni = leftAni;
        }
        else
        {
            nowAni = downAni;
        }

        // ë³€ê²½ ì• ë‹ˆë©”ì´ì…˜ ì ìš©
        if (nowAni != oldAni)
        {
            oldAni = nowAni;
            //GetComponent<Animator>().Play(nowAni);
        }
>>>>>>> 22ff9ed88032a66f3cc0fc3a068ec87347d487ea

    }

    private void FixedUpdate()
    {
<<<<<<< HEAD
        if (gameState != "playing") return; // °ÔÀÓÁßÀÌ ¾Æ´Ï¸é ½ÇÇà ¾ÈµÇ°Ô
       

        rb.velocity = new Vector2(axisH, axisV) * speed; // ÀÌµ¿
    }
=======
        if (gameState != "playing") return;
        if (inDamage)
        {
            //ë°ë¯¸ì§€ ë°›ëŠ” ì¤‘ì´ë©´ ê¹œë¹¡ê¹œë¹¡ ì´ê²Œ ë§Œë“¤ê¸°
            float val = Mathf.Sin(Time.time * 50);
            if (val > 0)
                gameObject.GetComponent<SpriteRenderer>().enabled = true;
            else
                gameObject.GetComponent<SpriteRenderer>().enabled = false;
            return;  //ë°ë¯¸ì§€ ë°›ê³  ìžˆì„ ë•Œ ì´ë™ ì•ˆë˜ê²Œ 

        }

        rb.velocity = new Vector2(axisH, axisV) * speed;
    }


    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "Enemy")  //ëª¬ìŠ¤í„°ì™€ ì ‘ì´‰ -ê³µê²©ë°›ìŒ
        {
            GetDamage(collision.gameObject);
            //inDamage = true;

        }
    }

    void GetDamage(GameObject Enemy)
    {
        if (gameState == "playing")
        {
            hp--;
            PlayerPrefs.SetInt("PlayerHP", hp);

        }
    }



    float GetAngle(Vector2 fromPt, Vector2 toPt) // ê°ë„ êµ¬í•˜ê¸°
    {
        float angle;
        if (axisH != 0 || axisV != 0)
        {
            float dx = toPt.x - fromPt.x;
            float dy = toPt.y - fromPt.y;
            float rad = Mathf.Atan2(dy, dx);

            angle = rad * Mathf.Rad2Deg;

        }

        else angle = angleZ;
        return angle;
    }

>>>>>>> 22ff9ed88032a66f3cc0fc3a068ec87347d487ea
}
